-- Fill this template with the real business data before importing.

insert into public.restaurants (
  slug,
  name,
  city,
  country_code,
  default_language,
  address,
  phone,
  whatsapp_number,
  hours,
  custom_link,
  google_place_id,
  google_review_url,
  tagline_tr,
  tagline_es,
  tagline_en,
  logo_image_url,
  cover_image_url,
  hero_video_url,
  social_links,
  theme,
  is_active,
  is_menu_enabled,
  is_feedback_enabled,
  is_game_enabled,
  promo_enabled,
  promo_threshold
) values (
  'real-kebab-istanbul',
  'Kebab Real Istanbul',
  'San Fernando',
  'ES',
  'es',
  'C. Real, 204, 11100 San Fernando, Cadiz, Spain',
  '+34 612 58 28 37',
  '34612582837',
  'Mar-Jue 13:00-16:00 · 20:00-00:00 · Vie-Sab hasta 00:30 · Dom hasta 00:00 · Lun cerrado',
  'https://www.realistanbul.es',
  '',
  'https://www.google.com/search?sa=X&sca_esv=1264130d37fc9ab6&sxsrf=ANbL-n7ewADy5m7bXPooo47dGDNtU5yIgQ:1777739716501&q=Kebab+Real+Istambul+Yorumlar&rflfq=1&num=20&stick=H4sIAAAAAAAAAONgkxK2NDE3sjQzMTQyMje1MDczMjAw3sDI-IpRxjs1KTFJISg1MUfBs7gkMTepNEchMr-oNDcnsWgRK15pAEyif5FYAAAA&rldimm=9472964122758762003&tbm=lcl&hl=tr-TR&ved=2ahUKEwjrk7jChJuUAxVaB9sEHWgZJuUQ9fQKegQIUBAG&biw=1536&bih=730&dpr=1.25#lkt=LocalPoiReviews',
  'San Fernando''da gercek Istanbul lezzeti.',
  'El autentico sabor de Estambul en San Fernando.',
  'Authentic Istanbul flavor in San Fernando.',
  '/brand/real-istanbul-logo-luxe.png',
  '/brand/real-istanbul-hero-kebab.png',
  '',
  '[
    {"label":"Instagram","url":"https://www.instagram.com/realistanbul.es"}
  ]'::jsonb,
  '{"primary":"#c9151b","accent":"#f5c542","fresh":"#138a50"}'::jsonb,
  true,
  true,
  true,
  true,
  false,
  90
)
on conflict (slug) do update set
  name = excluded.name,
  city = excluded.city,
  country_code = excluded.country_code,
  default_language = excluded.default_language,
  address = excluded.address,
  phone = excluded.phone,
  whatsapp_number = excluded.whatsapp_number,
  hours = excluded.hours,
  custom_link = excluded.custom_link,
  google_place_id = excluded.google_place_id,
  google_review_url = excluded.google_review_url,
  tagline_tr = excluded.tagline_tr,
  tagline_es = excluded.tagline_es,
  tagline_en = excluded.tagline_en,
  logo_image_url = excluded.logo_image_url,
  cover_image_url = excluded.cover_image_url,
  hero_video_url = excluded.hero_video_url,
  social_links = excluded.social_links,
  theme = excluded.theme,
  is_active = excluded.is_active,
  is_menu_enabled = excluded.is_menu_enabled,
  is_feedback_enabled = excluded.is_feedback_enabled,
  is_game_enabled = excluded.is_game_enabled,
  promo_enabled = excluded.promo_enabled,
  promo_threshold = excluded.promo_threshold;
